/**
  ******************************************************************************
  * @file    task5_fault_case.c
  * @brief   Task 5 fault case. DO NOT EDIT THIS FILE.
  *
  * It is applied only when RUN_TASK is 5, which runs the Task 4 program with
  * the fault in place. RUN_TASK 4 runs the same program without it.
  *
  * Task 5 is to diagnose the fault from MEASUREMENTS: what you expected, what
  * the board actually did, the first meaningful difference, and the register
  * and field responsible - and to explain electrically why the transaction
  * fails. Reading this file does not answer those questions.
  ******************************************************************************
  */

#include "prac2a.h"

void task5_fault_hook(void)
{
    volatile uint32_t * const reg = (volatile uint32_t *)0x40003800UL;
    uint32_t saved;

    if (run_task != 5u)
    {
        return;
    }

    saved = *reg;
    *reg = saved & ~0x00000040UL;
    *reg = (saved & ~0x00000040UL) | 0x00000001UL;
    *reg = saved | 0x00000001UL;
}
